name: Release UI bundle

on:
  push:
    branches:
      - '*'

jobs:
  release:
    permissions:
      contents: write
    
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
  
      - name: Install dependencies
        run: npm ci
  
      - name: Generate Antora UI Bundle
        run: gulp bundle
  
      - name: Generates Antora UI Preview
        run: gulp preview:build

      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          WITH_V: false

      - name: GH Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: |
            build/ui-bundle.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.bump.outputs.new_tag }}
          generate_release_notes: true
          draft: false
          prerelease: false
          
        